// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwUcppN7EX2EHYFa4a4EShGCtSHvVapbk',
    appId: '1:176275834940:web:45b20e9e88ad7d83809b39',
    messagingSenderId: '176275834940',
    projectId: 'fieldvisit-2e8e2',
    authDomain: 'fieldvisit-2e8e2.firebaseapp.com',
    storageBucket: 'fieldvisit-2e8e2.firebasestorage.app',
    measurementId: 'G-XC826GT0S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XmA0oRUc5IO24EwIoxWXZwozqGCbKYw',
    appId: '1:176275834940:android:988102a5d8bd07ee809b39',
    messagingSenderId: '176275834940',
    projectId: 'fieldvisit-2e8e2',
    storageBucket: 'fieldvisit-2e8e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP6mAZIcnuc8BG3AuDNn9A6tsGoXtoUyE',
    appId: '1:176275834940:ios:d53f22f4a007612e809b39',
    messagingSenderId: '176275834940',
    projectId: 'fieldvisit-2e8e2',
    storageBucket: 'fieldvisit-2e8e2.firebasestorage.app',
    iosBundleId: 'com.example.fieldVisit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP6mAZIcnuc8BG3AuDNn9A6tsGoXtoUyE',
    appId: '1:176275834940:ios:d53f22f4a007612e809b39',
    messagingSenderId: '176275834940',
    projectId: 'fieldvisit-2e8e2',
    storageBucket: 'fieldvisit-2e8e2.firebasestorage.app',
    iosBundleId: 'com.example.fieldVisit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwUcppN7EX2EHYFa4a4EShGCtSHvVapbk',
    appId: '1:176275834940:web:430e3faa05a00392809b39',
    messagingSenderId: '176275834940',
    projectId: 'fieldvisit-2e8e2',
    authDomain: 'fieldvisit-2e8e2.firebaseapp.com',
    storageBucket: 'fieldvisit-2e8e2.firebasestorage.app',
    measurementId: 'G-589QW5CQQL',
  );
}
